name: md5_file_checksum
description: Flutter plugin to calculate a file checksum as MD5 hash, using a platform native implementation.
version: 1.0.2
homepage: https://github.com/albemala/md5_file_checksum

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  pigeon: ^1.0.8

flutter:
  plugin:
    platforms:
      android:
        package: me.albemala.md5_file_checksum
        pluginClass: Md5FileChecksumPlugin
      ios:
        pluginClass: Md5FileChecksumPlugin
